# Generated by Django 3.2.7 on 2021-10-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_type_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
