# Generated by Django 3.2.7 on 2021-10-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_tech'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainphoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/main/')),
            ],
        ),
    ]
