# Generated by Django 3.2.7 on 2021-10-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_mainphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/posts/')),
                ('lead', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
    ]
