# Generated by Django 3.2.7 on 2021-10-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainphoto',
            name='image',
            field=models.ImageField(upload_to='../images/main/'),
        ),
    ]
