# Generated by Django 3.2.7 on 2021-10-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_mainphoto_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mainphoto',
        ),
    ]
