# Generated by Django 3.2.7 on 2021-10-25 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$', message='Username must be Alphanumeric')])),
                ('phone', models.CharField(max_length=9)),
            ],
        ),
    ]
